export const loginConstants = { 
    LOGIN_REQUEST: 'USER_LOGON_REQUEST',
    
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

    REGISTER_REQUEST: 'USER_REGISTER_REQUEST',

    REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

    LOGOUT: 'USER_LOGOUT'
}

export const homeConstants = {
    STAT_NEW: 'STAT_NEW',
    STAT_DELETE: 'STAT_DELETE',
    STAT_INCREMENT: 'STAT_INCREMENT',
    STAT_DECREMENT: 'STAT_DECREMENT',
    STAT_SELECT: 'STAT_SELECT',

    STAT_SUCCESS: 'STAT_SUCCESS',
    STAT_FAILURE: 'STAT_FAILURE',

    POST_SELECT: 'POST_SELECT',
    POST_NEW:'POST_NEW',
    POST_EDIT:'POST_EDIT',

    POST_FAILURE: 'POST_FAILURE',
    POST_SUCCESS: 'POST_SUCCESS'
}

export const accountConstants = {
    PWD_CHANGE: 'PWD_CHANGE',
    PWD_SUCCESS: 'PWD_SUCCESS',
    PWD_FAILURE: 'PWD_FAILURE',

    ICON_CHANGE: 'ICON_CHANGE',
    ICON_SUCCESS: 'ICON_SUCCESS',
    ICON_FAILURE: 'ICON_FAILURE'
}

export const HUGOConstants = {
    HUGO_ENTRY: 'NEW_HUGO_ENTRY',
    HUGO_ENTRY_FAILURE: 'HUGO_ENTRY_FAILURE',
    HUGO_ENTRY_SUCCESS: 'HUGO_ENTRY_SUCCESS',
    HUGO_ENTRY_DELETE: 'HUGO_ENTRY_DELETE'
}