# Generated by Django 2.2.10 on 2020-02-24 18:05

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import house_model.models.build


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateField()),
                ('image', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('source', djongo.models.fields.EmbeddedField(model_container=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_model.User'), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Builds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_build', djongo.models.fields.EmbeddedField(model_container=house_model.models.build.Build, null=True)),
                ('build_queue', djongo.models.fields.ArrayField(model_container=house_model.models.build.Build)),
                ('build_history', djongo.models.fields.ArrayField(model_container=house_model.models.build.Build)),
                ('build_ideas', djongo.models.fields.ArrayField(model_container=house_model.models.build.Build)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', djongo.models.fields.EmbeddedField(model_container=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_model.User'), null=True)),
                ('timeStamp', models.DateTimeField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('builds', djongo.models.fields.ArrayField(model_container=house_model.models.build.Build)),
                ('messages', djongo.models.fields.ArrayField(model_container=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_model.message'))),
            ],
        ),
    ]
